version: '3.9'

services:
  radarr:
    ports:
      - "7878:7878"
    depends_on:
      postgres:
        condition: service_healthy
    pull_policy: build
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - DBPASS=radarr
      - DBUSER=radarr
      - DBPORT=5432
      - DBHOST=postgres
      - PASSWORD=admin
      - APIKEY=a3fe3b50cbfb4f1c88933350584043c7
      - DOWNLOAD_URL=transmission
      - DOWNLOAD_PASSWORD=admin
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U radarr -d radarr-main" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=radarr
      - POSTGRES_USER=radarr
      - POSTGRES_MULTIPLE_DATABASES=radarr-main,radarr-log